routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Artisan;

/* Front Website All Route Start */





Route::get("reboot",function(){
    Artisan::call("view:clear");
    Artisan::call("route:clear");
    Artisan::call("config:cache");
    Artisan::call("cache:clear");
    Artisan::call("key:generate");
});

Route::get('migrate',function (){
    Artisan::call('migrate');
});



Route::get('dynamic-web','frontend\WebController@index');
Route::get('assign','frontend\WebController@assign');


Route::get('/','frontend\BasicController@index')->name('/');

Route::get('visit-category/{id}','frontend\ProductViewController@CategoryVisit')->name('visit.category');
Route::get('product-visit/{id}','frontend\ProductViewController@ProductVisit')->name('visit.product');
Route::get('order-product','frontend\CartController@order_product')->name('order.product');

/* Cart Start */

Route::namespace('frontend')->name('cart.')->group(function(){
    Route::post("/save-cart-item","CartController@store")->name('store');
    Route::post('/update-cart-item','CartController@updateCart')->name('update');
    Route::get('/carts','CartController@carts')->name('items');
    Route::post('/remove-cart-item','CartController@removeItem')->name('destroy');


    Route::post('/location-store','CartController@locationStore')->name('orderLocation');
    Route::get('/payment-option','CartController@paymentPage')->name('payment');
    Route::post('/confirm-order','CartController@confirmOrder')->name('complete-order');
    Route::get('/place-order','CartController@placeOrder')->name('placeorder');

});

/* Cart End*/

/*
Route::get('visit-category/{id}','frontend\BasicController@CategoryProductVisit')->name('visit.category');
Route::get('visit-category/{name}/{id}','frontend\BasicController@CategoryProductVisit')->name('productcategory.visit');*/

Route::get("single-product/{id}","frontend\BasicController@categoryProducts")->name('product.singlevisit');


Route::prefix('/CustomerRequest')->group(function(){
    Route::get('/visitor-messages','frontend\BasicController@Messages')->name('customer.message');
});

/*visitor text end */
/* Front Website All Route End */



Route::get('/about','frontend\BasicController@AboutMtr')->name('about');
Route::get('/contact','frontend\BasicController@Contact')->name('contact');
Route::get('/products','frontend\BasicController@product')->name('products');
Route::get('/service/{id}','frontend\BasicController@singleservice')->name('service.browse');



Auth::routes();

Route::middleware(['CheckPermit','auth'])->group(function(){

    Route::prefix('UserManagement')->group(function(){
        Route::get('/user-create','backend\UserController@index')->name('user.create');
        Route::post('/user-store','backend\UserController@store')->name('user.store');
        Route::get('/edit/{id}','backend\UserController@edit')->name('user.edit');
        Route::post('/erase','backend\UserController@destroy')->name('user.destroy');
        Route::post('/update-user/{id}','backend\UserController@update')->name('user.update');
        Route::get('/role-create','backend\RoleController@index')->name('role.create');
        Route::get('/role-view','backend\RoleController@view')->name('role.view');
        Route::post('/role-store','backend\RoleController@store')->name('role.store');
        Route::get('/role/edit/{id}','backend\RoleController@edit')->name('role.edit');
        Route::patch('/role/{id}/update','backend\RoleController@update')->name('role.update');
    });




    Route::prefix('SliderManagement')->group(function (){
        Route::get("Add-Slider","backend\SliderController@index")->name('slider.add');
        Route::post("store-Slider","backend\SliderController@store")->name('slider.store');
        Route::get("edit-Slider/{id}","backend\SliderController@edit")->name('slider.edit');
        Route::post("update-Slider/{id}","backend\SliderController@update")->name('slider.update');
        Route::post("destroy-Slider","backend\SliderController@destroy")->name('slider.destroy');
    });

    Route::prefix('Company')->group(function (){
        Route::get("edit-company/{id}","backend\SettingController@edit")->name('company.edit');
        Route::post("update-company/{id}","backend\SettingController@update")->name('company.update');
    });

    Route::prefix('dashboard')->group(function(){
        Route::get('/home', 'backend\AdminController@index')->name('home');

    });

    Route::prefix('ProductManagement')->group(function (){
        Route::get('/brand', 'backend\BrandController@index')->name('brand.add');
        Route::post('/brand/add', 'backend\BrandController@store')->name('brand.store');
        Route::get('/brand/{id}/Show', 'backend\BrandController@show')->name('brand.edit');
        Route::post('/erase', 'backend\BrandController@destroy')->name('brand.destroy');
        Route::post('/brand/update', 'backend\BrandController@update')->name('brand.update');

        /* Category Start */

        Route::get('/category', 'backend\CategoryController@index')->name('category.add');
        Route::post('/category/add', 'backend\CategoryController@store')->name('category.store');
        Route::get('/category/{id}/Show', 'backend\CategoryController@show')->name('category.edit');
        Route::post('/Category/erase', 'backend\CategoryController@destroy')->name('category.destroy');
        Route::post('/category/update', 'backend\CategoryController@update')->name('category.update');

        /* Category End */

        /* Sub-Category Start */

        Route::get('/sub-category', 'backend\SubCategoryController@index')->name('sub-category.add');
        Route::post('/sub-category/add', 'backend\SubCategoryController@store')->name('sub-category.store');
        Route::get('/sub-category/{id}/Edit', 'backend\SubCategoryController@show')->name('sub-category.edit');
        Route::post('/sub-Category/erase', 'backend\SubCategoryController@destroy')->name('sub-category.destroy');
        Route::post('/sub-category/update', 'backend\SubCategoryController@update')->name('sub-category.update');

        /* Sub-Category End */

        /* Product Add */

        Route::get('/product', 'backend\ProductController@index')->name('product.add');
        Route::get('/product/view', 'backend\ProductController@viewproduct')->name('product.view');
        Route::post('product/add', 'backend\ProductController@store')->name('product.store');
        Route::get('/product/{id}/Show', 'backend\ProductController@show')->name('product.edit');
        Route::post('/Product/erase', 'backend\ProductController@destroy')->name('product.destroy');
        Route::post('/product/update', 'backend\ProductController@update')->name('product.update');
        Route::post('/status-update', 'backend\ProductController@status_update')->name('product.statusupdate');

        Route::post('/search-category', 'backend\ProductController@searchsubcategory')->name('purchase.subcategory');


        /* Product End */

        /* Product Size Start */

        Route::get('/size', 'backend\SizeController@index')->name('size.add');
        Route::post('/add', 'backend\SizeController@store')->name('size.store');
        Route::get('/size/{id}/Show', 'backend\SizeController@show')->name('size.edit');
        Route::post('/Size/erase', 'backend\SizeController@destroy')->name('size.destroy');
        Route::post('/size/update', 'backend\SizeController@update')->name('size.update');


    });

    Route::prefix('Offer')->group(function (){
        Route::get('view-offer', 'backend\OfferController@index')->name('offer.index');
        Route::post('store-offer', 'backend\OfferController@store')->name('offer.store');
        Route::get('edit-offer/{id}', 'backend\OfferController@edit')->name('offer.edit');
        Route::post('update-offer/', 'backend\OfferController@update')->name('offer.update');
        Route::post('delete-offer', 'backend\OfferController@destroy')->name('offer.delete');

        Route::get('manage-offer', 'backend\OfferController@manage')->name('offer.manage');
        Route::post('load-product', 'backend\OfferController@load_product')->name('load.product');
        Route::post('create-offer', 'backend\OfferController@create_offer')->name('create.offer');
        Route::post('Offer/edit-offer-product/{id}', 'backend\OfferController@offerProduct_edit')->name('offer_product.edit');
        Route::post('Offer/delete-offer-product', 'backend\OfferController@offerProduct_delete')->name('offer_product.delete');

        Route::get('coupon', 'backend\OfferController@coupon')->name('coupon');
        Route::post('coupon', 'backend\OfferController@coupon')->name('coupon.store');
    });


    Route::prefix('WebManagement')->group(function () {

        /* Team Start */

        Route::get("/add-team","backend\TeamController@index")->name('team.add');
        Route::get("/edit/{id}","backend\TeamController@show")->name('team.edit');
        Route::post("/save-team","backend\TeamController@store")->name('team.store');
        Route::post("/update-team","backend\TeamController@update")->name('team.update');
        Route::post("/erase","backend\TeamController@destroy")->name('team.destroy');

        /* service Start */

        Route::get("/add-service","backend\ServiceController@index")->name('service.add');
        Route::get("/edit-service/{id}","backend\ServiceController@show")->name('service.edit');
        Route::post("/save-service","backend\ServiceController@store")->name('service.store');
        Route::post("/update-service/{id}","backend\ServiceController@update")->name('service.update');

resources/views/front/pages/order-2.blade.php
@extends('front.layouts.master')
<?php
use App\helper\Helpers\Helper;
$helpers = new Helper();
?>

@section('title',$helpers->titles()->where('page',1)->first())
@section('content')
	<main class="col px-5 pl-md-2 pt-2 main">
		<!--main-area-->

		<div class="container p-4">
			<div class="container">
				<div class="stepwizard">
					<div class="stepwizard-row">
						<div class="stepwizard-step">
							<button type="button" class="btn btn-danger btn-circle" >1</button>
							<p>Sigin in/Register</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-primary btn-circle" disabled="disabled">2</button>
							<p>Location Confermation</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-default btn-circle" disabled="disabled">3</button>
							<p>Order Overview</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-default btn-circle" disabled="disabled">4</button>
							<p>Payment Option</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-default btn-circle" disabled="disabled">5</button>
							<p>Order Placed</p>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
						<div class="col-md-6  text-center offset-md-3">
							<h1 class="p-4">You Have to Confirm Your Location</h1>
							<div class="row">

								<div class="col-sm-12">
									<form action="{{ route('cart.orderLocation') }}" method="post" class=" p-4
									needs-validation" novalidate>
                                        @csrf
										<div class="form-row">
											<div class="col-md-11 m-2">
												<label for="mobile" class="font-weight-bold">Your Phone No.</label>
												<input
                                                    type="tel"
                                                    class="form-control"
                                                    id="mobile"
                                                    placeholder="Enter Your Phone Number e.g +880123456789"
                                                    name="mobile"
                                                    pattern="[0-9]{11}"
                                                    required>
												<div class="valid-feedback">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
											<div class="col-md-11 m-2">
												<label for="district" class="font-weight-bold">Select District:</label>
												<select name="district" class="form-control" id="district" required>
													<option>--Select District--</option>
													<option>Chittagong</option>
													<option>Dhaka</option>
												</select>
												<div class="valid-feedback">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
											<div class="col-md-11 m-2">
												<label for="thana" class="font-weight-bold">Select Thana:</label>
												<select class="form-control" name="thana" id="thana" required>
													<option>--Select Thana--</option>
													<option>Chadgaon</option>
													<option>Bakalia</option>
												</select>
												<div class="valid-feedback" class="font-weight-bold">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
											<div class="col-md-11 m-2">
												<label for="adress" class="font-weight-bold">Your Adress</label>
												<textarea
                                                    class="form-control"
                                                    name="address"
                                                    id="address"
                                                    placeholder="Enter address"
                                                    required></textarea>
												<div class="valid-feedback">Valid.</div>
												<div class="invalid-feedback">Please fill out this field.</div>
											</div>
										</div>
										<div class="col-md-11 m-2">
											<input type="submit" class="btn btn-lg text-light m-2 btn-danger"
                                               value="Confirm" />
										</div>


									</form>
								</div>
							</div>
						</div>

					</div>

@stop

resources/views/front/pages/order-3.blade.php
@extends('front.layouts.master')
<?php
use App\helper\Helpers\Helper;
$helpers = new Helper();
?>

@section('title',$helpers->titles()->where('page',1)->first())
@section('content')
	<main class="col px-5 pl-md-2 pt-2 main">
		<!--main-area-->
		<div class="container p-4">
			<div class="container">
				<div class="stepwizard">
					<div class="stepwizard-row">
						<div class="stepwizard-step">
							<button type="button" class="btn btn-danger btn-circle" >1</button>
							<p>Sigin in/Register</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-danger btn-circle" disabled="disabled">2</button>
							<p>Location Confermation</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-primary btn-circle" disabled="disabled">3</button>
							<p>Order Overview</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-default btn-circle" disabled="disabled">4</button>
							<p>Payment Option</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-default btn-circle" disabled="disabled">5</button>
							<p>Order Placed</p>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6  text-center offset-md-3">
					<h1 class="p-4">Confirm Your Order</h1>
					<div class="row">

						<div class="col-sm-12">
							<form action="/action_page.php" class=" p-4 needs-validation" novalidate>
								<div class="form-row">
									<div class="col-md-11 m-2">
										<table class="show-cart table">

										</table>
										<div class="font-weight-bold">Total price: ৳<span class="total-cart text-danger"></span>/-</div>

									</div>
								</div>
								<div class="col-md-11 m-2">
									<a type="submit" class="btn btn-lg text-light m-2 btn-danger" href="order-4.html">Confirm</a>
								</div>


							</form>
						</div>
					</div>
				</div>

			</div>

@stop

resources/views/front/pages/order-4.blade.php
@extends('front.layouts.master')
<?php
use App\helper\Helpers\Helper;
$helpers = new Helper();
?>

@section('title',$helpers->titles()->where('page',1)->first())
@section('content')
			<main class="col px-5 pl-md-2 pt-2 main">
				<!--main-area-->
				<div class="container p-4">
					<div class="container">
						<div class="stepwizard">
							<div class="stepwizard-row">
								<div class="stepwizard-step">
									<button type="button" class="btn btn-danger btn-circle" >1</button>
									<p>Sigin in/Register</p>
								</div>
								<div class="stepwizard-step">
									<button type="button" class="btn btn-danger btn-circle" disabled="disabled">2</button>
									<p>Location Confermation</p>
								</div>
								<div class="stepwizard-step">
									<button type="button" class="btn btn-danger btn-circle" disabled="disabled">3</button>
									<p>Order Overview</p>
								</div>
								<div class="stepwizard-step">
									<button type="button" class="btn btn-primary btn-circle" disabled="disabled">4</button>
									<p>Payment Option</p>
								</div>
								<div class="stepwizard-step">
									<button type="button" class="btn btn-default btn-circle" disabled="disabled">5</button>
									<p>Order Placed</p>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6  text-center offset-md-3">
							<h1 class="p-4">Confirm Your Order</h1>
							<div class="row">

								<div class="col-sm-12">
									<form action="{{ route('cart.complete-order') }}" method="post" class=" p-4
									needs-validation"
                                          novalidate>
                                        @csrf
										<div class="form-row">
											<div class="col-md-11 m-2">
												<div class="form-check">
													<label class="form-check-label form-inline">
														<input type="radio" value="1" checked class="form-check-input"
                                                               name="payment">Cash On Delivery &nbsp;&nbsp; <span><img src="img/png/cash-on-delivery.png" alt=""></span>
													</label>
												</div>
												<div class="form-check">
													<label class="form-check-label form-inline">
														<input type="radio" value="2" class="form-check-input"
                                                               name="payment">Bkash &nbsp;&nbsp; <span><img src="img/png/bkash.png" alt=""></span>
													</label>
												</div>
											</div>
										</div>
										<div class="col-md-11 m-2">
											<input
                                                type="submit"
                                                class="btn btn-lg text-light m-2 btn-danger"
                                                value="Confirm" />
										</div>


									</form>
								</div>
							</div>
						</div>

					</div>
@stop

resources/views/front/pages/order-5.blade.php
@extends('front.layouts.master')
<?php
use App\helper\Helpers\Helper;
$helpers = new Helper();
?>

@section('title',$helpers->titles()->where('page',1)->first())
@section('content')
	<main class="col px-5 pl-md-2 pt-2 main">
		<!--main-area-->
		<div class="container p-4">
			<div class="container">
				<div class="stepwizard">
					<div class="stepwizard-row">
						<div class="stepwizard-step">
							<button type="button" class="btn btn-danger btn-circle" >1</button>
							<p>Sigin in/Register</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-danger btn-circle" disabled="disabled">2</button>
							<p>Location Confermation</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-danger btn-circle" disabled="disabled">3</button>
							<p>Order Overview</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-danger btn-circle" disabled="disabled">4</button>
							<p>Payment Option</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-success btn-circle" disabled="disabled">5</button>
							<p>Order Placed</p>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6  text-center offset-md-3 p-4">
					<h1 class="p-4">Your Order Has been Confirmed</h1>
					<h4 class="p-4 text-secondery">Your Order your order will be placed within 1 hour</h4>
					<div class="container">
						<span class="check mark bg-danger text-light rounded-circle "><i class="fas fa-check"></i></span>
					</div>
				</div>

			</div>

@stop

resources/views/front/pages/order.blade.php
@extends('front.layouts.master')
<?php
use App\helper\Helpers\Helper;
$helpers = new Helper();
?>

@section('title',$helpers->titles()->where('page',1)->first())
@section('content')
	<main class="col px-5 pl-md-2 pt-2 main">
		<!--main-area-->

		<div class="container p-4">
			<div class="container">
				<div class="stepwizard">
					<div class="stepwizard-row">
						<div class="stepwizard-step">
							<button type="button" class="btn btn-primary btn-circle" >1</button>
							<p>Sigin in/Register</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-default btn-circle" disabled="disabled">2</button>
							<p>Location Confermation</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-default btn-circle" disabled="disabled">3</button>
							<p>Order Overview</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-default btn-circle" disabled="disabled">4</button>
							<p>Payment Option</p>
						</div>
						<div class="stepwizard-step">
							<button type="button" class="btn btn-default btn-circle" disabled="disabled">5</button>
							<p>Order Placed</p>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6  text-center offset-md-3">
					<h1 class="p-4">At First You Have to Sign In</h1>
					<div class="row">
						<div class="col-sm-11">
							<a href="#" class="btn btn-block m-2 btn-primary"><span class="text-light"><i class="fab fa-facebook"></i></span>&nbsp; SIgn In With Facebook</a>
						</div>
						<div class="col-sm-11">
							<a href="#" class="btn btn-block m-2 btn-danger"><span class="text-light"><i class="fas fa-envelope"></i></span>&nbsp; SIgn In With Gmail</a>

						</div>

						<div class="col-sm-12">
							<form action="/action_page.php" class=" p-4 needs-validation" novalidate>
								<div class="form-row">
									<div class="col-md-11 m-2">
										<input type="tel" class="form-control" id="mobile" placeholder="Enter Your Phone Number e.g +880123456789" name="mobile" pattern="[0-9]{11}"required>
										<div class="valid-feedback">Valid.</div>
										<div class="invalid-feedback">Please fill out this field.</div>
									</div>
									<div class="col-md-11 m-2">
										<input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
										<div class="valid-feedback">Valid.</div>
										<div class="invalid-feedback">Please fill out this field.</div>
									</div>
								</div>
								<div class="col-md-11 m-2">
									<a type="submit" class="btn btn-lg text-light m-2 btn-primary" href="{{ route
									('login')
									}}">Sign
                                        In</a>
								</div>
								<div class="col-md-11 m-2">
									<a type="submit" class="btn btn-lg text-light m-2 btn-danger" href="{{ route
									('register')

									}}">Register</a>
								</div>


							</form>
						</div>
					</div>
				</div>

			</div>

@stop

resources/views/front/pages/view-product.blade.php
@extends('front.layouts.master')
<?php
	use App\helper\Helpers\Helper;
	$helpers = new Helper();
?>

@section('title',$helpers->titles()->where('page',1)->first())
@section('content')
	<main class="col px-5 pl-md-2 pt-2 main">
		<div class="main-pading-area">
				<!--main-area-->
				<div class="1st-offer img-fluid p-4">
					<div class="container">
						<div class="row">
							<div class="col-md-6 col-xs-12"><img class="img-fluid" src="img/ofr-2.jpg" alt=""></div>

							<div class="col-md-6 col-xs-12"><img class="img-fluid" src="img/ofr-1.jpg" alt=""></div>
						</div>
					</div>
				</div>

				<!--body area-->
				<div class="locator-section">
					<div class="container">
						<ul class="breadcrumb">
							<li class="breadcrumb-item"><a href="baby_care.html">{{$category->name}} /</a></li>

						</ul>
					</div>
				</div>

				<div class="product-page product text-center m-4">
					<h1 class="text-dark p-4 border-bottom">{{$category->name}}</h1>
					<div class="container">
						<div class="row">
							@foreach($products as $product)
							<div class="col-md-3 col-sm-4 col-6">
								<div class="card shopping-card">
									<div class="card-body">
										@php
											$image = \App\ImageProduct::query()->where('product_id', $product->id)->first();
										@endphp

										<img class="card-img-top img-fluid " src="{{asset('public/admin/product/'.$image->image)}}">
										<h4 class="card-title">{{$product->name}}</h4>
										{{--<small class="card-text">200 &nbsp;gm</small>--}}
										<h6 class="card-text font-weight-bold">{{$product->price}}&nbsp;৳</h6>
										<div class="h-a">

											<button type="button" class="btn-block align-middle btn btn-light mt-5 details" data-toggle="modal" data-target="#myModalDetails" data-id="{{$product->id}}">Details <span class="mx-auto"><i class="fas fa-angle-double-right"></i></span>
											</button>
										</div>
									</div>
									<div class="add-rmv-area  justify-content-center">
										<form class="form-inline d-j d-block" id="d-b">
											<button
													type="button"
													data-name="{{$product->name}}"
                                                    data-price="{{$product->price}}"
													data-id="{{ $product->id }}"
													class="
													    btn btn-warning btn-lg  p-0
													    cartMinus
													    inputValues
                                                        details-add-rmv-btn
                                                    ">
												<i class="fas fa-minus"></i>
                                            </button>

											<input
                                                type="text"
                                                class="
                                                    inputValues midValue
                                                    form-control qty{{$product->id}}
                                                    bg-warning
                                                    text-light
                                                    details-add-rmv-btn
                                                "
												   value="0 in bag"
												   data-id="{{$product->id}}"
                                                   data-qty="0"
												   readonly>
											<button
													data-id="{{ $product->id }}"
													type="button"
													data-name="{{$product->name}}"
                                                    data-price="{{$product->price}}"
													class="btn details-add-rmv-btn inputValues btn-warning btn-lg details-add-rmv-btn p-0
													cartPlus">
												<i class="fas fa-plus"></i>
                                            </button>
										</form>
										{{--<a href="#" data-name="{{$product->name}}"
                                           data-price="{{$product->price}}"
                                           class="add-to-cart cart-b add-btn btn btn-light text-danger font-weight-bold"
                                            data-id="{{$product->id}}"
                                        >
                                            Add to bag
                                        </a>--}}

									</div>
								</div>
							</div>
							@endforeach
						</div>
					</div>
				</div>
@endsection
@section('js')

{{--
    <script>
        $(document).ready(function(){
            sessionStorage.clear();
            carts();
        });

        $(document).on("click",".cartMinus",function(){
            var product_id = $(this).attr('data-id');

            const qty = $(".qty"+product_id).attr("data-qty");

            var incQty = (qty>0 ? Number(qty)-1 : 0);

            $(".qty"+product_id).attr({"data-qty":incQty});

            $(".qty"+product_id).val(incQty+ " in bag");

        });

        $(document).on("click",".cartPlus",function(){
            var product_id = $(this).attr('data-id');

            const qty = $(".qty"+product_id).attr("data-qty");

            var incQty = (qty>=0 ? Number(qty)+1 : 0);

            $(".qty"+product_id).attr({"data-qty":incQty});

            $(".qty"+product_id).val(incQty+ " in bag");

            if(incQty >0){
                storeToCart(product_id,incQty);
            }

            console.log("Plus : ",product_id+" Qty is : "+incQty);
        });

        function storeToCart(product_id,qty){
            $.ajax({
                method:"post",
                url : "{{ route('cart.store') }}",
                data:{product_id:product_id,qty:qty,_token:"{{csrf_token()}}"},
                dataType:"json",
                success:function(res){

                    console.log("success");
                    carts();
                }
            })
        }

        function carts(){
            sessionStorage.clear();

            $.ajax({
                method:"get",
                url : "{{ route('cart.items') }}",
                dataType:"json",
                success:function(res){
                    console.log(res);
                    $(".show-cart").html(res.items);
                    $(".total-cart").text(res.totalAmount);
                    $(".total-item").text(res.totalItem);

                }
            })
        };


        /* remove item from carts */

            $(document).on("click",".destroyItem",function(){
                var product_id = $(this).attr('data-id');

                $.ajax({
                    method:"post",
                    url :"{{ route('cart.destroy') }}",
                    data : {product_id:product_id,_token:'{{ csrf_token() }}'},
                    dataType:'json',
                    success:function(res){
                        carts();
                        console.log(res);
                    }
                })
        });


    </script>
--}}

@endsection